service: disputer1

queue:
  dev: risk-nonprod-ci

steps:
  - step: bash
    command:
      - export ENVIRONMENT=stg
        - npm install
        - npm run test
    flavour: node12
    properties:
      env:
        CONFIG: dev